INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('.', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('.', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('test', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('test', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/@modal', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/@modal', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/berkantdural', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/boek', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/book', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/booking-success', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/haartransplantatie/[country]/[tier]', 'nl', 'Haartransplantatie', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/haartransplantatie/[country]/[tier]', 'en', 'Haartransplantatie', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/missie', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/mission', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/ozlemdural', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/ozlemdural', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/reborn', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/reborn', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/recharge', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/recharge', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/rescue', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/rescue', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/contact', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/how', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/methods', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/methods', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/methods/reborn', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/methods/reborn', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/methods/recharge', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/methods/recharge', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/v6-hairboost/methods/rescue', 'nl', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/methods/rescue', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/mission', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/v6-hairboost/reviews', 'en', 'V6 Hairboost', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('nl/[...slug]', 'nl', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.pages (slug, language, category, status, updated_at) VALUES ('en/[...slug]', 'en', 'Other', 'published', NOW()) ON CONFLICT (slug) DO NOTHING;